framework:
    messenger:
        transports:
            product_updated:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\EventMessageSerializer
                options:
                    auto_setup: true
                    confirm_timeout: 2
                    exchange:
                        name: '%evotym_shared.rabbitmq.product_exchange%'
                        type: '%evotym_shared.rabbitmq.product_exchange_type%'
                        default_publish_routing_key: '%evotym_shared.rabbitmq.product_updated_routing_key%'
                    queues:
                        '%evotym_shared.rabbitmq.order_product_sync_queue%':
                            binding_keys: ['%evotym_shared.rabbitmq.product_updated_routing_key%']

            order_processing_status:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\EventMessageSerializer
                options:
                    auto_setup: true
                    confirm_timeout: 2
                    exchange:
                        name: order.processing.status.events
                        type: direct
                        default_publish_routing_key: order.processing.status
                    queues:
                        order.processing.status:
                            binding_keys: ['order.processing.status']

            order_created:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\EventMessageSerializer
                failure_transport: order_created_failed
                retry_strategy:
                    max_retries: 5
                    delay: 1000
                    multiplier: 2
                    max_delay: 30000
                options:
                    auto_setup: true
                    confirm_timeout: 2
                    exchange:
                        name: order.events
                        type: direct
                    queues:
                        order.created:
                            binding_keys: ['order.created']

            order_created_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Messenger\EventMessageSerializer
                options:
                    auto_setup: true
                    confirm_timeout: 2
                    exchange:
                        name: order.events.dlq
                        type: direct
                        default_publish_routing_key: order.created.failed
                    queues:
                        order.created.failed:
                            binding_keys: ['order.created.failed']

        routing:
            App\Message\ProductUpdatedMessage: product_updated
            App\Message\OrderProcessingStatusMessage: order_processing_status
